### ISSUE TITLE
Is the cow quote meant to be Times New Roman?

### ISSUE THREAD

**Issue by willthames** [ansible-community/community-website#218]
I'd expect the cow quote to be monospace (or at least sans-serif to match the other text)

I wonder if I'm missing a font, which means the fallback font choices might need to improved?

**Comment by willthames** [comment]
<img width="329" alt="Screenshot 2023-09-29 at 9 09 35 am" src="https://github.com/ansible-community/community-website/assets/391807/05e48203-acad-40e3-912b-7f2d092e38da">

**Comment by oraNod** [comment]
Hey @willthames Thanks for reporting this issue. It definitely shouldn't be Times New Roman. That svg uses a Red Hat font so it probably is the fallback font choice.

**Comment by oraNod** [comment]
This issue should be fixed now. @willthames Any chance you could verify on this preview build? https://ansible-community-website--224.org.readthedocs.build/en/224/

That svg should be using this font family now: `"RedHatDisplay, Helvetica Neue, Helvetica, Arial, sans-serif;"`. Hopefully no more Times New Roman.

**Comment by willthames** [comment]
@oraNod Just checked on my phone, still the same unfortunately

![IMG_2260](https://github.com/ansible-community/community-website/assets/391807/eb49ddc0-c598-43e2-8350-af84ae75b111)
